sudo: required
services:
  - docker

before_install:
  - docker build -t jans888/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jans888/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-2-184480728634"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"